#!/usr/bin/env python3
"""Fail-closed current-integration blocker audit for six AGY proxy claims."""
from __future__ import annotations
import argparse,json,pathlib,re,subprocess,sys,time,urllib.request
ROOT=pathlib.Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
from tools.analysis.experiment_provenance import build_provenance,canonical_json_sha256,provenance_complete,sha256_file
TASK_ID="BACKLOG-AGY-SYSTEM-BLOCKERS-02";SRC="/home/augus/src/slop.cpp-main"
EXPECTED={ROOT/"config/research_backlog_admissions/BACKLOG-AGY-SYSTEM-BLOCKERS-01.json":"b4a82e5c3ea49d081216ccc555972efece9a22a3a4f97aa8dd4d0ade7f0e8e10",ROOT/"runs/research/BACKLOG-AGY-SYSTEM-BLOCKERS-01/PRE_REGISTRATION.md":"a6ce6a423f56d9b3328943fd984bd1df84b735667dc1af747da858f7248355ef",ROOT/"runs/research/SLX-03-STATE-WRITE-ELISION-2026-08-25/raw/receipt.json":"10a7ea78bcf66991700ca40d217e1e7e83b0f2d25ee1e45fc651c3399b68d5a9",ROOT/"tools/probes/slx03_state_write_oracle.py":"b398b691268baf3f933a9fd45a36ad71e86c62fc6e4fdb02467ea8e0531a3e74",ROOT/"runs/research/SLX-07-H2O-EVICTION-2026-08-25/raw/receipt.json":"405072005b7b17897b3a46200d53f204366b2fbe148113e69039d5b6f283f198",ROOT/"tools/probes/slx07_h2o_eviction_oracle.py":"98af7d6e56cec47d481154ef0ddc41e4654d0cb79f3b22466e92f9337ad3376d",ROOT/"runs/research/REP-04-KVARN-NATIVE-KERNEL-2026-08-25/raw/receipt.json":"66c163d2d161041caae80aed3e1c8689f48522ba3c197f96b8fef07e531898c8",ROOT/"tools/probes/rep04_kvarn_native_kernel.py":"0093f09b1b9f7055a6b0fab565014cf03db3726ed878b829ebc84e3072eb0ac8",ROOT/"runs/research/REP-05-LAYERWISE-PRECISION-2026-08-25/raw/receipt.json":"9c23e665e02fdfc8fd03c21e58f183bfcf8f1dee435803f1b51b705c0b74e040",ROOT/"tools/probes/rep05_layerwise_kv_precision.py":"9787da10ad8026df424f295f91618d8525928d5c218c1f9d2a3f6333de5b4067",ROOT/"runs/research/RETRO-01-RECURRENT-RETROFIT-2026-08-25/raw/receipt.json":"c3092d2fdb6a46067794af5d79e2684fd7722a383bc0f223a0fbe76f876af42f",ROOT/"tools/probes/retro01_recurrent_retrofit.py":"2328c1b83273811117234b5f7ffd95404efcdea103f6ce98c33e5b1bf0f6874d",ROOT/"runs/research/SLX-08-SPECULATIVE-PREFILL-2026-08-25/raw/receipt.json":"f19600ed451d5ed4ad3a24b5c29ef3fbcf2a95de06ffcab0aef9a7e9152cb78a",ROOT/"tools/probes/slx08_speculative_prefill_oracle.py":"5b85dd266c3fc72ae47a7cabe6e5ae3246e4aab544e87e6ee7cd47eab81bdc37"}
EXPECTED.pop(ROOT/"config/research_backlog_admissions/BACKLOG-AGY-SYSTEM-BLOCKERS-01.json")
EXPECTED.pop(ROOT/"runs/research/BACKLOG-AGY-SYSTEM-BLOCKERS-01/PRE_REGISTRATION.md")
EXPECTED[ROOT/"config/research_backlog_admissions/BACKLOG-AGY-SYSTEM-BLOCKERS-02.json"]="82839d015cab78bca0970cc3fc86391b8ead96e17fb5a0ccd2fbb4f70bb0621a"
EXPECTED[ROOT/"runs/research/BACKLOG-AGY-SYSTEM-BLOCKERS-02/PRE_REGISTRATION.md"]="e3cbb48fbd84f17d900998b215afa01ea90281e861f39dbcc9f7bc156f7ec68f"
ITEMS={
"SLX-03":{"pattern":r"state[-_ ]write[-_ ]elision|elision[_ -]n16|ephemeral[_ -]eos","unlock":"compiled recurrent-state write cadence/elision in the deployed decode path plus hardware write counters"},
"SLX-07":{"pattern":r"\bh2o\b|heavy[-_ ]hitter|heavy hitter oracle","unlock":"H2O attention-score accumulator and eviction policy integrated into the deployed KV lifecycle"},
"REP-04":{"pattern":r"\bkvarn\b|kvarn[_ -]","unlock":"native fused KVarN attention/dequantization kernel callable by the deployed runtime"},
"REP-05":{"pattern":r"layerwise.{0,40}cache.{0,20}(type|precision)|per[-_ ]layer.{0,30}(kv|cache)","unlock":"per-layer KV precision allocator/CLI and physical mixed-precision cache buffers"},
"RETRO-01":{"pattern":r"recurrent.{0,30}retrofit|retrofit.{0,30}recurrent","unlock":"trained recurrent-retrofit checkpoint with immutable model identity and runnable inference route"},
"SLX-08":{"pattern":r"speculative.{0,30}prefill|prefill.{0,30}speculative|selected[-_ ]block.{0,30}(qkv|prefill)","unlock":"selected-block speculative-prefill implementation wired into real TTFT"}}
def write(p,v):p.write_text(json.dumps(v,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
def run(argv,timeout=180):
 if argv[:4]==["wsl","-d","Ubuntu-24.04","--"]:argv=[*argv[:3],"-e",*argv[4:]]
 d=subprocess.run(argv,capture_output=True,text=True,encoding="utf-8",errors="replace",check=False,timeout=timeout);return {"argv":argv,"returncode":d.returncode,"stdout":d.stdout.strip(),"stderr":d.stderr.strip()}
def health(port):
 try:
  with urllib.request.urlopen(f"http://127.0.0.1:{port}/health",timeout=10) as r:return r.status
 except Exception:return None
def service():
 x=run(["wsl","-d","Ubuntu-24.04","--","systemctl","show","llm-inference.service","-p","MainPID","-p","NRestarts","-p","ActiveState","-p","ExecStart","--no-pager"]);return {"command":x,"values":dict(line.split("=",1) for line in x["stdout"].splitlines() if "=" in line)}
def execute(outdir):
 raw=outdir/"raw";started=time.strftime("%Y-%m-%dT%H:%M:%SZ",time.gmtime());mono=time.monotonic();ledger={}
 if any(raw.iterdir()):raise RuntimeError("raw not empty")
 for p,e in EXPECTED.items():
  a=sha256_file(p)
  if a!=e:raise ValueError(f"hash mismatch {p}: {a}")
  ledger[p.relative_to(ROOT).as_posix()]={"bytes":p.stat().st_size,"sha256":a}
 before=service();exec_start=before["values"].get("ExecStart","");binary=exec_start.split("path=",1)[1].split(" ;",1)[0];binary_hash=run(["wsl","-d","Ubuntu-24.04","--","sha256sum",binary]);help_row=run(["wsl","-d","Ubuntu-24.04","--",binary,"--help"]);strings_row=run(["wsl","-d","Ubuntu-24.04","--","strings",binary]);git_head=run(["wsl","-d","Ubuntu-24.04","--","git","-C",SRC,"rev-parse","HEAD"]);git_status=run(["wsl","-d","Ubuntu-24.04","--","git","-C",SRC,"status","--porcelain"])
 if help_row["returncode"] not in (0,1) or strings_row["returncode"] or git_head["returncode"] or git_status["returncode"]:raise RuntimeError("identity/search bootstrap failed")
 inventory=run(["wsl","-d","Ubuntu-24.04","--","bash","-lc","find /home/augus/models -type f 2>/dev/null | grep -Ei 'retrofit|recurrent.*(checkpoint|model)|hybrid.*retrofit' || true"])
 rows=[]
 for item,spec in ITEMS.items():
  grep=run(["wsl","-d","Ubuntu-24.04","--","git","-C",SRC,"grep","-n","-i","-E",spec["pattern"],"--","src","tools/server"])
  if grep["returncode"] not in (0,1):raise RuntimeError(f"git grep failed {item}: {grep}")
  surface="\n".join((help_row["stdout"],help_row["stderr"],strings_row["stdout"]));binary_matches=[line for line in surface.splitlines() if re.search(spec["pattern"],line,re.I)][:50];source_matches=grep["stdout"].splitlines();artifact_matches=inventory["stdout"].splitlines() if item=="RETRO-01" else []
  missing=not binary_matches and not source_matches and not artifact_matches
  rows.append({"item":item,"pattern":spec["pattern"],"binary_matches":binary_matches,"source_matches":source_matches,"artifact_matches":artifact_matches,"missing_integration":missing,"unlock_criterion":spec["unlock"]})
 after=service();runtime_unchanged=int(before["values"].get("MainPID")==after["values"].get("MainPID") and before["values"].get("ExecStart")==after["values"].get("ExecStart") and health(8080)==200 and health(8081)==200);metrics={"audited_items":len(rows),"missing_integration_count":sum(r["missing_integration"] for r in rows),"proxy_only_predecessors":6,"runtime_unchanged":runtime_unchanged}
 write(raw/"samples.json",rows);write(raw/"actual_scores.json",metrics);write(raw/"artifact_hashes.json",ledger|{"deployed_binary":{"sha256":binary_hash["stdout"].split()[0]},"candidate_source":{"git_head":git_head["stdout"],"git_status":git_status["stdout"]}});write(raw/"dataset_hashes.json",{"search_spec_semantic_sha256":canonical_json_sha256(ITEMS)});write(raw/"failure_reproduction.json",{"predecessors":"Python proxy/oracle implementations","physical_requirement":"deployed implementation or immutable trained artifact","blockers":rows});write(raw/"falsifiable_hypothesis.json",{"items":list(ITEMS),"positive_match_invalidates_blocker":True});write(raw/"hardware_metrics.json",{"not_executed_because_no_callable_physical_route":True});write(raw/"independent_evaluation.json",{"deployed_help":help_row,"candidate_git_head":git_head,"candidate_git_status":git_status,"model_inventory":inventory});write(raw/"invalidation_rules.json",{"any_positive_match_fails_objective_absence_gate":True,"ambiguous_match_aborts":True});write(raw/"invariant_controls.json",{"source_root":SRC,"binary":binary,"patterns":{k:v["pattern"] for k,v in ITEMS.items()}});write(raw/"paired_baseline.json",{"proxy_receipts":[p.relative_to(ROOT).as_posix() for p in EXPECTED if p.name=="receipt.json"],"physical_successors":[]});write(raw/"real_implementation.json",{"callable_features":{r["item"]:not r["missing_integration"] for r in rows},"global_kv_types_do_not_satisfy_rep05":True,"generic_hadamard_does_not_satisfy_rep04":True});write(raw/"semantic_parity.json",{"not_applicable_until_physical_route_exists":True});write(raw/"service_maintenance.json",{"read_only":True,"before":before,"after":after,"runtime_unchanged":runtime_unchanged});write(raw/"source_execution_receipt.json",{"predecessor_receipts":{p.parent.parent.name:e for p,e in EXPECTED.items() if p.name=="receipt.json"}})
 defs={"scope_coverage":("audited_items","eq",6),"objective_absence":("missing_integration_count","eq",6),"probe_classification":("proxy_only_predecessors","eq",6),"runtime_integrity":("runtime_unchanged","eq",1)};gates={g:{"metric":m,"operator":"eq","threshold":t,"actual":metrics[m],"pass":metrics[m]==t} for g,(m,_,t) in defs.items()};evidence={"acceptance_gates":"raw/receipt.json","actual_scores":"raw/actual_scores.json","artifact_hashes":"raw/artifact_hashes.json","dataset_hashes":"raw/dataset_hashes.json","failure_reproduction":"raw/failure_reproduction.json","falsifiable_hypothesis":"raw/falsifiable_hypothesis.json","hardware_metrics":"raw/hardware_metrics.json","independent_evaluation":"raw/independent_evaluation.json","invalidation_rules":"raw/invalidation_rules.json","invariant_controls":"raw/invariant_controls.json","paired_baseline":"raw/paired_baseline.json","provenance":"raw/receipt.json","raw_samples":"raw/samples.json","real_implementation":"raw/real_implementation.json","receipt_fingerprint":"raw/receipt.json","semantic_parity":"raw/semantic_parity.json","service_maintenance":"raw/service_maintenance.json","source_execution_receipt":"raw/source_execution_receipt.json"};files=sorted({raw/v.removeprefix("raw/") for v in evidence.values() if v!="raw/receipt.json"});prov=build_provenance(script_path=pathlib.Path(__file__).resolve(),started_at_utc=started,started_monotonic=mono,input_paths=[*EXPECTED,*files],packages=["pytest"],runtime={"execution_mode":"read_only_integration_blocker_audit","binary":binary,"source_git_head":git_head["stdout"]});ok,errors=provenance_complete(prov)
 if not ok:raise ValueError(errors)
 receipt={"schema":"local-labs-backlog-receipt-v1","task_id":TASK_ID,"provenance":prov,"provenance_complete":True,"gates":gates,"evidence":evidence};receipt["receipt_fingerprint"]=canonical_json_sha256(receipt);write(raw/"receipt.json",receipt);return receipt,metrics,rows
def main():
 p=argparse.ArgumentParser();p.add_argument("--outdir",type=pathlib.Path,default=ROOT/"runs/research"/TASK_ID);a=p.parse_args();r,m,rows=execute(a.outdir.resolve());failed=[g for g,x in r["gates"].items() if not x["pass"]];(a.outdir/"RESULT.md").write_text("# "+TASK_ID+" result\n\n`AGY_SYSTEM_BLOCKERS_REGISTERED_R1` pending independent AGY review.\n\n"+"\n".join(f"- {x['item']}: {'BLOCKED' if x['missing_integration'] else 'MATERIALIZABLE'}; unlock: {x['unlock_criterion']}" for x in rows)+f"\n\nFailed gates: {', '.join(failed) if failed else 'none'}. These are current integration blockers, not scientific rejections.\n",encoding="utf-8");print(json.dumps({"metrics":m,"gates":r["gates"],"rows":rows},indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
