import json
b0={"t000":{"winner":"1","reason":"Sharper imagery, bookended rain metaphor for closure."},"t004":{"winner":"2","reason":"More inventive body-horror imagery."},"t008":{"winner":"1","reason":"Grounded autobiographical detail, stronger payoff."},"t012":{"winner":"2","reason":"Escalates inventively, page-turning callback."},"t016":{"winner":"2","reason":"More vivid images, sharper central line."},"t020":{"winner":"2","reason":"Sharper, more surprising insults."},"t024":{"winner":"2","reason":"Rain motif, tighter structure."},"t028":{"winner":"1","reason":"Time-as-fuel conceit more coherent/original."},"t032":{"winner":"1","reason":"Concedes nuance before rebutting; more rhetorical craft."}}
b1={"t001":{"winner":"1","reason":"Wittier variety of targets; strong close."},"t005":{"winner":"tie","reason":"Near-identical technique and quality."},"t009":{"winner":"2","reason":"Clearer philosophical arc, sharper hook."},"t013":{"winner":"2","reason":"Named POV adds emotional throughline."},"t017":{"winner":"2","reason":"Richer voice, morally complex turn."},"t021":{"winner":"1","reason":"More culinarily literate jokes."},"t025":{"winner":"1","reason":"Tighter unity around one controlling symbol."},"t029":{"winner":"2","reason":"Sharper wordplay, genre nod."},"t033":{"winner":"2","reason":"More elegant conceit for the soul's price."}}
b2={"t002":{"winner":"1","reason":"More original imagery, sustained voice."},"t006":{"winner":"1","reason":"Tighter comic rhythm; R2 tonal misstep."},"t010":{"winner":"2","reason":"Coherent extended metaphor, tonal control."},"t014":{"winner":"2","reason":"More original thesis, tighter conceit."},"t018":{"winner":"1","reason":"Tighter thesis with concrete examples."},"t022":{"winner":"2","reason":"Cohesive callback structure."},"t026":{"winner":"2","reason":"Sustains one financial metaphor end to end."},"t030":{"winner":"2","reason":"Sharper opening image; avoids jarring simile."},"t034":{"winner":"2","reason":"More varied gags, richer framing device."}}
b3={"t003":{"winner":"1","reason":"Sharper, more original images."},"t007":{"winner":"2","reason":"More vivid insults, escalating callbacks."},"t011":{"winner":"2","reason":"Stronger sensory staging, sharper character beat."},"t015":{"winner":"1","reason":"More inventive central conceit."},"t019":{"winner":"1","reason":"Cinematic staging, honor-among-thieves logic."},"t023":{"winner":"2","reason":"Tighter comic construction, clean callback."},"t027":{"winner":"2","reason":"Embedded memory gives emotional stakes."},"t031":{"winner":"2","reason":"More consistent visceral body-horror imagery."},"t035":{"winner":"1","reason":"Richer noir voice, bookending rain motif, mercy beat."}}
allv={**b0,**b1,**b2,**b3}
assert len(allv)==36, len(allv)
json.dump(allv, open('runs/a2/gate3/claude_verdicts_pairwise.json','w'), indent=1)
print("wrote 36 verdicts")
